export const CATEGORIES_AND_SUBCATEGORIES_LOADED =
  "ADD_CATEGORIES_AND_SUBCATEGORIES";
export const CATEGORIES_AND_SUBCATEGORIES_LOADING =
  "CATEGORIES_AND_SUBCATEGORIES_LOADING";
export const CATEGORIES_AND_SUBCATEGORIES_FAILED =
  "CATEGORIES_AND_SUBCATEGORIES_FAILED";
export const ADD_SUBCATEGORIES_MAP = "ADD_SUBCATEGORIES_MAP";
